quarkus:
  datasource:
    db-kind: postgresql
    username: oliver
    password: 5xb7iPPiSM85TqWE
    jdbc:
      url: jdbc:postgresql://192.168.1.230:5432/pizzeria
  hibernate-orm:
    database:
      generation: update
    log:
      sql: true
    sql-load-script: import.sql
  http:
    port: 8080
    cors: true
  log:
    level: INFO
    category:
      "com.pizzeria": DEBUG 